//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helios.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class BILET
    {
        public BILET()
        {
            this.WYKUP_BILET = new HashSet<WYKUP_BILET>();
        }
    
        [Display(Name="Id")]
        public int IdBiletu { get; set; }
        [Display(Name="Rodzaj")]
        public string NazwaBiletu { get; set; }
        [Display(Name="cena")]
        public decimal Cena { get; set; }
    
        public virtual ICollection<WYKUP_BILET> WYKUP_BILET { get; set; }
    }
}
