//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helios.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class ETAT
    {
        public ETAT()
        {
            this.PRACOWNIK = new HashSet<PRACOWNIK>();
        }
    
        [Display(Name="Id")]
        public int IdEtatu { get; set; }

        [Display(Name="Nazwa etatu")]
        public string NazwaEtatu { get; set; }

        [Display(Name="P³aca min.")]
        public decimal PlacaMin { get; set; }

        [Display(Name="P³aca max.")]
        public decimal PlacaMax { get; set; }
    
        public virtual ICollection<PRACOWNIK> PRACOWNIK { get; set; }
    }
}
