//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helios.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class FILM
    {
        public FILM()
        {
            this.SEANS = new HashSet<SEANS>();
            this.OBSLUGA = new HashSet<OBSLUGA>();
        }
        [Display(Name="Id")]
        public int IdFilmu { get; set; }

        [Display(Name="Tytu³ PL")]
        public string NazwaFilmuPL { get; set; }
        [Display(Name="Tytu³ ORG")]
        public string NazwaFilmuORG { get; set; }
        [Display(Name="2D/3D")]
        public string RodzajFilmu { get; set; }
        [Display(Name="Czas trwania")]
        public Nullable<System.TimeSpan> CzasTrwania { get; set; }
    
        public virtual ICollection<SEANS> SEANS { get; set; }
        public virtual ICollection<OBSLUGA> OBSLUGA { get; set; }
    }
}
