//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeliosEntities : DbContext
    {
        public HeliosEntities()
            : base("name=HeliosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        // odpowiadaja za poszczegolne tabele - zbiory - punkty wejscia w bazie danhych
        public DbSet<BILET> BILET { get; set; }
        public DbSet<ETAT> ETAT { get; set; }
        public DbSet<FILM> FILM { get; set; }
        public DbSet<KINO> KINO { get; set; }
        public DbSet<MIEJSCE> MIEJSCE { get; set; }
        public DbSet<OBSLUGA> OBSLUGA { get; set; }
        public DbSet<PRACOWNIK> PRACOWNIK { get; set; }
        public DbSet<SALA> SALA { get; set; }
        public DbSet<SEANS> SEANS { get; set; }
        public DbSet<WYKUP_BILET> WYKUP_BILET { get; set; }
    }
}
