//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KINO
    {
        public KINO()
        {
            this.SALA = new HashSet<SALA>();
            this.PRACOWNIK = new HashSet<PRACOWNIK>();
        }
    
        public int IdKina { get; set; }
        public string NazwaKina { get; set; }
        public string KodPocztowy { get; set; }
        public string Miejscowosc { get; set; }
        public string Ulica { get; set; }
        public string Nr { get; set; }
        public string Telefon { get; set; }
    
        public virtual ICollection<SALA> SALA { get; set; }
        public virtual ICollection<PRACOWNIK> PRACOWNIK { get; set; }
    }
}
