//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helios.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class MIEJSCE
    {
        public MIEJSCE()
        {
            this.WYKUP_BILET = new HashSet<WYKUP_BILET>();
        }
    
        public int IdMiejsca { get; set; }
        [Display(Name="Rz¹d")]
        public int Rzad { get; set; }
        [Display(Name="Miejsce")]
        public int Miejsce1 { get; set; }
        public Nullable<bool> Status_M { get; set; }
        public int FK_IdSali { get; set; }
    
        public virtual ICollection<WYKUP_BILET> WYKUP_BILET { get; set; }
        public virtual SALA SALA { get; set; }
    }
}
