//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helios.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class PRACOWNIK
    {
        public PRACOWNIK()
        {
            this.OBSLUGA = new HashSet<OBSLUGA>();
        }
    
        [Display(Name="Id")]
        public int IdPracownika { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string KodPocztowy { get; set; }
        public string Miejscowosc { get; set; }
        public string Ulica { get; set; }
        public string Nr { get; set; }
        public string Telefon { get; set; }
        public decimal PlacaPod { get; set; }
        public Nullable<decimal> PlacaDod { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Data urodzenia")]
        public Nullable<System.DateTime> DataUr { get; set; }

        
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name="Data zatrudnienia")]
        public Nullable<System.DateTime> DataZat { get; set; }
        public int FK_IdEtatu { get; set; }
        public int FK_IdKina { get; set; }
    
        public virtual ETAT ETAT { get; set; }
        public virtual KINO KINO { get; set; }
        public virtual ICollection<OBSLUGA> OBSLUGA { get; set; }
    }
}
